//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

DATA LCDATA1<>+0x000(SB)/8, $0x0d0c090805040100
DATA LCDATA1<>+0x008(SB)/8, $0x0000000000000000
GLOBL LCDATA1<>(SB), 8, $16

TEXT ·_update_hidden(SB), $72-56

	MOVQ previous_outputs+0(FP), DI
	MOVQ update_indices+8(FP), SI
	MOVQ update_coeffs+16(FP), DX
	MOVQ update_size+24(FP), CX
	MOVQ weights+32(FP), R8
	MOVQ outputs+40(FP), R9
	MOVQ outputs_len+48(FP), R10
	ADDQ $8, SP
	MOVQ R10, 56(SP)
	LEAQ LCDATA1<>(SB), BP

	LONG $0x2404894c             // mov    qword [rsp], r8
	LONG $0x24548948; BYTE $0x30 // mov    qword [rsp + 48], rdx
	LONG $0x24748948; BYTE $0x28 // mov    qword [rsp + 40], rsi
	LONG $0x38247c83; BYTE $0x00 // cmp    dword 56[rsp], 0 /* [rbp + 16] */
	JLE  LBB0_33
	LONG $0x3824448b             // mov    eax, dword 56[rsp] /* [rbp + 16] */
	WORD $0x8941; BYTE $0xc7     // mov    r15d, eax
	WORD $0xf883; BYTE $0x20     // cmp    eax, 32
	JAE  LBB0_3
	WORD $0xc031                 // xor    eax, eax
	JMP  LBB0_9

LBB0_3:
	WORD $0x8944; BYTE $0xf8     // mov    eax, r15d
	WORD $0xe083; BYTE $0xe0     // and    eax, -32
	LONG $0xe0508d48             // lea    rdx, [rax - 32]
	WORD $0x8949; BYTE $0xd2     // mov    r10, rdx
	LONG $0x05eac149             // shr    r10, 5
	LONG $0x01c28349             // add    r10, 1
	WORD $0x8548; BYTE $0xd2     // test    rdx, rdx
	JE   LBB0_34
	WORD $0x894d; BYTE $0xd3     // mov    r11, r10
	LONG $0xfee38349             // and    r11, -2
	WORD $0xf749; BYTE $0xdb     // neg    r11
	WORD $0xdb31                 // xor    ebx, ebx
	LONG $0x456ff9c5; BYTE $0x00 // vmovdqa    xmm0, oword 0[rbp] /* [rip + .LCPI0_0] */

LBB0_5:
	LONG $0x0c6ffac5; BYTE $0x9f               // vmovdqu    xmm1, oword [rdi + 4*rbx]
	LONG $0x546ffac5; WORD $0x109f             // vmovdqu    xmm2, oword [rdi + 4*rbx + 16]
	LONG $0x5c6ffac5; WORD $0x209f             // vmovdqu    xmm3, oword [rdi + 4*rbx + 32]
	LONG $0x646ffac5; WORD $0x309f             // vmovdqu    xmm4, oword [rdi + 4*rbx + 48]
	LONG $0x0069e2c4; BYTE $0xd0               // vpshufb    xmm2, xmm2, xmm0
	LONG $0x0071e2c4; BYTE $0xc8               // vpshufb    xmm1, xmm1, xmm0
	LONG $0xca6cf1c5                           // vpunpcklqdq    xmm1, xmm1, xmm2
	LONG $0x0059e2c4; BYTE $0xd0               // vpshufb    xmm2, xmm4, xmm0
	LONG $0x0061e2c4; BYTE $0xd8               // vpshufb    xmm3, xmm3, xmm0
	LONG $0xd26ce1c5                           // vpunpcklqdq    xmm2, xmm3, xmm2
	LONG $0x5c6ffac5; WORD $0x509f             // vmovdqu    xmm3, oword [rdi + 4*rbx + 80]
	LONG $0x0061e2c4; BYTE $0xd8               // vpshufb    xmm3, xmm3, xmm0
	LONG $0x646ffac5; WORD $0x409f             // vmovdqu    xmm4, oword [rdi + 4*rbx + 64]
	LONG $0x0059e2c4; BYTE $0xe0               // vpshufb    xmm4, xmm4, xmm0
	LONG $0xdb6cd9c5                           // vpunpcklqdq    xmm3, xmm4, xmm3
	LONG $0x646ffac5; WORD $0x709f             // vmovdqu    xmm4, oword [rdi + 4*rbx + 112]
	LONG $0x0059e2c4; BYTE $0xe0               // vpshufb    xmm4, xmm4, xmm0
	LONG $0x6c6ffac5; WORD $0x609f             // vmovdqu    xmm5, oword [rdi + 4*rbx + 96]
	LONG $0x0051e2c4; BYTE $0xe8               // vpshufb    xmm5, xmm5, xmm0
	LONG $0xe46cd1c5                           // vpunpcklqdq    xmm4, xmm5, xmm4
	LONG $0x7f7ac1c4; WORD $0x590c             // vmovdqu    oword [r9 + 2*rbx], xmm1
	LONG $0x7f7ac1c4; WORD $0x5954; BYTE $0x10 // vmovdqu    oword [r9 + 2*rbx + 16], xmm2
	LONG $0x7f7ac1c4; WORD $0x595c; BYTE $0x20 // vmovdqu    oword [r9 + 2*rbx + 32], xmm3
	LONG $0x7f7ac1c4; WORD $0x5964; BYTE $0x30 // vmovdqu    oword [r9 + 2*rbx + 48], xmm4
	QUAD $0x0000809f8c6ffac5; BYTE $0x00       // vmovdqu    xmm1, oword [rdi + 4*rbx + 128]
	QUAD $0x0000909f946ffac5; BYTE $0x00       // vmovdqu    xmm2, oword [rdi + 4*rbx + 144]
	QUAD $0x0000a09f9c6ffac5; BYTE $0x00       // vmovdqu    xmm3, oword [rdi + 4*rbx + 160]
	QUAD $0x0000b09fa46ffac5; BYTE $0x00       // vmovdqu    xmm4, oword [rdi + 4*rbx + 176]
	LONG $0x0069e2c4; BYTE $0xd0               // vpshufb    xmm2, xmm2, xmm0
	LONG $0x0071e2c4; BYTE $0xc8               // vpshufb    xmm1, xmm1, xmm0
	LONG $0xca6cf1c5                           // vpunpcklqdq    xmm1, xmm1, xmm2
	LONG $0x0059e2c4; BYTE $0xd0               // vpshufb    xmm2, xmm4, xmm0
	LONG $0x0061e2c4; BYTE $0xd8               // vpshufb    xmm3, xmm3, xmm0
	LONG $0xd26ce1c5                           // vpunpcklqdq    xmm2, xmm3, xmm2
	QUAD $0x0000d09f9c6ffac5; BYTE $0x00       // vmovdqu    xmm3, oword [rdi + 4*rbx + 208]
	LONG $0x0061e2c4; BYTE $0xd8               // vpshufb    xmm3, xmm3, xmm0
	QUAD $0x0000c09fa46ffac5; BYTE $0x00       // vmovdqu    xmm4, oword [rdi + 4*rbx + 192]
	LONG $0x0059e2c4; BYTE $0xe0               // vpshufb    xmm4, xmm4, xmm0
	LONG $0xdb6cd9c5                           // vpunpcklqdq    xmm3, xmm4, xmm3
	QUAD $0x0000f09fa46ffac5; BYTE $0x00       // vmovdqu    xmm4, oword [rdi + 4*rbx + 240]
	LONG $0x0059e2c4; BYTE $0xe0               // vpshufb    xmm4, xmm4, xmm0
	QUAD $0x0000e09fac6ffac5; BYTE $0x00       // vmovdqu    xmm5, oword [rdi + 4*rbx + 224]
	LONG $0x0051e2c4; BYTE $0xe8               // vpshufb    xmm5, xmm5, xmm0
	LONG $0xe46cd1c5                           // vpunpcklqdq    xmm4, xmm5, xmm4
	LONG $0x7f7ac1c4; WORD $0x594c; BYTE $0x40 // vmovdqu    oword [r9 + 2*rbx + 64], xmm1
	LONG $0x7f7ac1c4; WORD $0x5954; BYTE $0x50 // vmovdqu    oword [r9 + 2*rbx + 80], xmm2
	LONG $0x7f7ac1c4; WORD $0x595c; BYTE $0x60 // vmovdqu    oword [r9 + 2*rbx + 96], xmm3
	LONG $0x7f7ac1c4; WORD $0x5964; BYTE $0x70 // vmovdqu    oword [r9 + 2*rbx + 112], xmm4
	LONG $0x40c38348                           // add    rbx, 64
	LONG $0x02c38349                           // add    r11, 2
	JNE  LBB0_5
	LONG $0x01c2f641                           // test    r10b, 1
	JE   LBB0_8

LBB0_7:
	LONG $0x046ffac5; BYTE $0x9f               // vmovdqu    xmm0, oword [rdi + 4*rbx]
	LONG $0x4c6ffac5; WORD $0x109f             // vmovdqu    xmm1, oword [rdi + 4*rbx + 16]
	LONG $0x546ffac5; WORD $0x209f             // vmovdqu    xmm2, oword [rdi + 4*rbx + 32]
	LONG $0x5c6ffac5; WORD $0x309f             // vmovdqu    xmm3, oword [rdi + 4*rbx + 48]
	LONG $0x656ff9c5; BYTE $0x00               // vmovdqa    xmm4, oword 0[rbp] /* [rip + .LCPI0_0] */
	LONG $0x0071e2c4; BYTE $0xcc               // vpshufb    xmm1, xmm1, xmm4
	LONG $0x0079e2c4; BYTE $0xc4               // vpshufb    xmm0, xmm0, xmm4
	LONG $0xc16cf9c5                           // vpunpcklqdq    xmm0, xmm0, xmm1
	LONG $0x0061e2c4; BYTE $0xcc               // vpshufb    xmm1, xmm3, xmm4
	LONG $0x0069e2c4; BYTE $0xd4               // vpshufb    xmm2, xmm2, xmm4
	LONG $0xc96ce9c5                           // vpunpcklqdq    xmm1, xmm2, xmm1
	LONG $0x546ffac5; WORD $0x509f             // vmovdqu    xmm2, oword [rdi + 4*rbx + 80]
	LONG $0x0069e2c4; BYTE $0xd4               // vpshufb    xmm2, xmm2, xmm4
	LONG $0x5c6ffac5; WORD $0x409f             // vmovdqu    xmm3, oword [rdi + 4*rbx + 64]
	LONG $0x0061e2c4; BYTE $0xdc               // vpshufb    xmm3, xmm3, xmm4
	LONG $0xd26ce1c5                           // vpunpcklqdq    xmm2, xmm3, xmm2
	LONG $0x5c6ffac5; WORD $0x709f             // vmovdqu    xmm3, oword [rdi + 4*rbx + 112]
	LONG $0x0061e2c4; BYTE $0xdc               // vpshufb    xmm3, xmm3, xmm4
	LONG $0x6c6ffac5; WORD $0x609f             // vmovdqu    xmm5, oword [rdi + 4*rbx + 96]
	LONG $0x0051e2c4; BYTE $0xe4               // vpshufb    xmm4, xmm5, xmm4
	LONG $0xdb6cd9c5                           // vpunpcklqdq    xmm3, xmm4, xmm3
	LONG $0x7f7ac1c4; WORD $0x5904             // vmovdqu    oword [r9 + 2*rbx], xmm0
	LONG $0x7f7ac1c4; WORD $0x594c; BYTE $0x10 // vmovdqu    oword [r9 + 2*rbx + 16], xmm1
	LONG $0x7f7ac1c4; WORD $0x5954; BYTE $0x20 // vmovdqu    oword [r9 + 2*rbx + 32], xmm2
	LONG $0x7f7ac1c4; WORD $0x595c; BYTE $0x30 // vmovdqu    oword [r9 + 2*rbx + 48], xmm3

LBB0_8:
	WORD $0x394c; BYTE $0xf8 // cmp    rax, r15
	JE   LBB0_10

LBB0_9:
	LONG $0x8714b70f             // movzx    edx, word [rdi + 4*rax]
	LONG $0x14894166; BYTE $0x41 // mov    word [r9 + 2*rax], dx
	LONG $0x01c08348             // add    rax, 1
	WORD $0x3949; BYTE $0xc7     // cmp    r15, rax
	JNE  LBB0_9

LBB0_10:
	LONG $0x38247c83; BYTE $0x00 // cmp    dword 56[rsp], 0 /* [rbp + 16] */
	JLE  LBB0_33
	WORD $0xc985                 // test    ecx, ecx
	JLE  LBB0_33
	WORD $0xc989                 // mov    ecx, ecx
	LONG $0x79048d4b             // lea    rax, [r9 + 2*r15]
	LONG $0x24448948; BYTE $0x10 // mov    qword [rsp + 16], rax
	LONG $0x24148b48             // mov    rdx, qword [rsp]
	LONG $0x7a048d4a             // lea    rax, [rdx + 2*r15]
	LONG $0x24448948; BYTE $0x20 // mov    qword [rsp + 32], rax
	WORD $0x8944; BYTE $0xf8     // mov    eax, r15d
	WORD $0xe083; BYTE $0xc0     // and    eax, -64
	WORD $0x8944; BYTE $0xff     // mov    edi, r15d
	WORD $0xe783; BYTE $0xf8     // and    edi, -8
	WORD $0x894d; BYTE $0xf8     // mov    r8, r15
	WORD $0xf749; BYTE $0xd8     // neg    r8
	LONG $0x60728d48             // lea    rsi, [rdx + 96]
	LONG $0x24748948; BYTE $0x08 // mov    qword [rsp + 8], rsi
	LONG $0x02c28348             // add    rdx, 2
	LONG $0x24548948; BYTE $0x18 // mov    qword [rsp + 24], rdx
	WORD $0x3145; BYTE $0xe4     // xor    r12d, r12d
	LONG $0x245c634c; BYTE $0x38 // movsxd    r11, dword 56[rsp] /* [rbp + 16] */
	JMP  LBB0_14

LBB0_13:
	LONG $0x01c48349         // add    r12, 1
	WORD $0x3949; BYTE $0xcc // cmp    r12, rcx
	JE   LBB0_33

LBB0_14:
	LONG $0x24548b48; BYTE $0x28 // mov    rdx, qword [rsp + 40]
	LONG $0x2cbf0f4e; BYTE $0x62 // movsx    r13, word [rdx + 2*r12]
	LONG $0xebaf0f4d             // imul    r13, r11
	LONG $0x24548b48; BYTE $0x30 // mov    rdx, qword [rsp + 48]
	LONG $0x14be0f46; BYTE $0x22 // movsx    r10d, byte [rdx + r12]
	LONG $0x38247c83; BYTE $0x08 // cmp    dword 56[rsp], 8 /* [rbp + 16] */
	JB   LBB0_15
	LONG $0x24148b48             // mov    rdx, qword [rsp]
	LONG $0x6a348d4e             // lea    r14, [rdx + 2*r13]
	LONG $0x24548b48; BYTE $0x20 // mov    rdx, qword [rsp + 32]
	LONG $0x6a148d4a             // lea    rdx, [rdx + 2*r13]
	WORD $0x394c; BYTE $0xca     // cmp    rdx, r9
	JBE  LBB0_19
	LONG $0x24743b4c; BYTE $0x10 // cmp    r14, qword [rsp + 16]
	JAE  LBB0_19

LBB0_15:
	WORD $0xdb31 // xor    ebx, ebx

LBB0_28:
	WORD $0x8948; BYTE $0xda     // mov    rdx, rbx
	LONG $0x01c7f641             // test    r15b, 1
	JE   LBB0_30
	LONG $0x2b148d4a             // lea    rdx, [rbx + r13]
	LONG $0x24348b48             // mov    rsi, qword [rsp]
	LONG $0x5614b70f             // movzx    edx, word [rsi + 2*rdx]
	LONG $0xaf0f4166; BYTE $0xd2 // imul    dx, r10w
	LONG $0x14014166; BYTE $0x59 // add    word [r9 + 2*rbx], dx
	WORD $0x8948; BYTE $0xda     // mov    rdx, rbx
	LONG $0x01ca8348             // or    rdx, 1

LBB0_30:
	WORD $0xf748; BYTE $0xd3     // not    rbx
	WORD $0x394c; BYTE $0xc3     // cmp    rbx, r8
	JE   LBB0_13
	LONG $0x24748b48; BYTE $0x18 // mov    rsi, qword [rsp + 24]
	LONG $0x6e1c8d4a             // lea    rbx, [rsi + 2*r13]

LBB0_32:
	LONG $0x5374b70f; BYTE $0xfe   // movzx    esi, word [rbx + 2*rdx - 2]
	LONG $0xaf0f4166; BYTE $0xf2   // imul    si, r10w
	LONG $0x34014166; BYTE $0x51   // add    word [r9 + 2*rdx], si
	LONG $0x5334b70f               // movzx    esi, word [rbx + 2*rdx]
	LONG $0xaf0f4166; BYTE $0xf2   // imul    si, r10w
	LONG $0x74014166; WORD $0x0251 // add    word [r9 + 2*rdx + 2], si
	LONG $0x02c28348               // add    rdx, 2
	WORD $0x3949; BYTE $0xd7       // cmp    r15, rdx
	JNE  LBB0_32
	JMP  LBB0_13

LBB0_19:
	LONG $0x38247c83; BYTE $0x40 // cmp    dword 56[rsp], 64 /* [rbp + 16] */
	JAE  LBB0_21
	WORD $0xd231                 // xor    edx, edx
	JMP  LBB0_25

LBB0_21:
	LONG $0x6e79c1c4; BYTE $0xc2   // vmovd    xmm0, r10d
	LONG $0xc070fbc5; BYTE $0x00   // vpshuflw    xmm0, xmm0, 0
	LONG $0xc070f9c5; BYTE $0x00   // vpshufd    xmm0, xmm0, 0
	LONG $0x187de3c4; WORD $0x01c0 // vinsertf128    ymm0, ymm0, xmm0, 1
	LONG $0x24548b48; BYTE $0x08   // mov    rdx, qword [rsp + 8]
	LONG $0x6a1c8d4a               // lea    rbx, [rdx + 2*r13]
	WORD $0xd231                   // xor    edx, edx

LBB0_22:
	LONG $0x44d579c5; WORD $0xa053             // vpmullw    xmm8, xmm0, oword [rbx + 2*rdx - 96]
	LONG $0x197de3c4; WORD $0x01c2             // vextractf128    xmm2, ymm0, 1
	LONG $0x5cd5e9c5; WORD $0xb053             // vpmullw    xmm3, xmm2, oword [rbx + 2*rdx - 80]
	LONG $0x4cd579c5; WORD $0xc053             // vpmullw    xmm9, xmm0, oword [rbx + 2*rdx - 64]
	LONG $0x6cd5e9c5; WORD $0xd053             // vpmullw    xmm5, xmm2, oword [rbx + 2*rdx - 48]
	LONG $0x54d579c5; WORD $0xe053             // vpmullw    xmm10, xmm0, oword [rbx + 2*rdx - 32]
	LONG $0x7cd5e9c5; WORD $0xf053             // vpmullw    xmm7, xmm2, oword [rbx + 2*rdx - 16]
	LONG $0x1cd579c5; BYTE $0x53               // vpmullw    xmm11, xmm0, oword [rbx + 2*rdx]
	LONG $0x54d5e9c5; WORD $0x1053             // vpmullw    xmm2, xmm2, oword [rbx + 2*rdx + 16]
	LONG $0xfd61c1c4; WORD $0x515c; BYTE $0x10 // vpaddw    xmm3, xmm3, oword [r9 + 2*rdx + 16]
	LONG $0xfd39c1c4; WORD $0x5124             // vpaddw    xmm4, xmm8, oword [r9 + 2*rdx]
	LONG $0xfd51c1c4; WORD $0x516c; BYTE $0x30 // vpaddw    xmm5, xmm5, oword [r9 + 2*rdx + 48]
	LONG $0xfd31c1c4; WORD $0x5174; BYTE $0x20 // vpaddw    xmm6, xmm9, oword [r9 + 2*rdx + 32]
	LONG $0xfd41c1c4; WORD $0x517c; BYTE $0x50 // vpaddw    xmm7, xmm7, oword [r9 + 2*rdx + 80]
	LONG $0xfd29c1c4; WORD $0x514c; BYTE $0x40 // vpaddw    xmm1, xmm10, oword [r9 + 2*rdx + 64]
	LONG $0xfd6941c4; WORD $0x5144; BYTE $0x70 // vpaddw    xmm8, xmm2, oword [r9 + 2*rdx + 112]
	LONG $0xfd21c1c4; WORD $0x5154; BYTE $0x60 // vpaddw    xmm2, xmm11, oword [r9 + 2*rdx + 96]
	LONG $0x7f7ac1c4; WORD $0x5124             // vmovdqu    oword [r9 + 2*rdx], xmm4
	LONG $0x7f7ac1c4; WORD $0x515c; BYTE $0x10 // vmovdqu    oword [r9 + 2*rdx + 16], xmm3
	LONG $0x7f7ac1c4; WORD $0x5174; BYTE $0x20 // vmovdqu    oword [r9 + 2*rdx + 32], xmm6
	LONG $0x7f7ac1c4; WORD $0x516c; BYTE $0x30 // vmovdqu    oword [r9 + 2*rdx + 48], xmm5
	LONG $0x7f7ac1c4; WORD $0x514c; BYTE $0x40 // vmovdqu    oword [r9 + 2*rdx + 64], xmm1
	LONG $0x7f7ac1c4; WORD $0x517c; BYTE $0x50 // vmovdqu    oword [r9 + 2*rdx + 80], xmm7
	LONG $0x7f7ac1c4; WORD $0x5154; BYTE $0x60 // vmovdqu    oword [r9 + 2*rdx + 96], xmm2
	LONG $0x7f7a41c4; WORD $0x5144; BYTE $0x70 // vmovdqu    oword [r9 + 2*rdx + 112], xmm8
	LONG $0x40c28348                           // add    rdx, 64
	WORD $0x3948; BYTE $0xd0                   // cmp    rax, rdx
	JNE  LBB0_22
	WORD $0x394c; BYTE $0xf8                   // cmp    rax, r15
	JE   LBB0_13
	WORD $0x8948; BYTE $0xc2                   // mov    rdx, rax
	WORD $0x8948; BYTE $0xc3                   // mov    rbx, rax
	LONG $0x38c7f641                           // test    r15b, 56
	JE   LBB0_28

LBB0_25:
	LONG $0x6e79c1c4; BYTE $0xc2 // vmovd    xmm0, r10d
	LONG $0xc070fbc5; BYTE $0x00 // vpshuflw    xmm0, xmm0, 0
	LONG $0xc070f9c5; BYTE $0x00 // vpshufd    xmm0, xmm0, 0

LBB0_26:
	LONG $0xd579c1c4; WORD $0x560c // vpmullw    xmm1, xmm0, oword [r14 + 2*rdx]
	LONG $0xfd71c1c4; WORD $0x510c // vpaddw    xmm1, xmm1, oword [r9 + 2*rdx]
	LONG $0x7f7ac1c4; WORD $0x510c // vmovdqu    oword [r9 + 2*rdx], xmm1
	LONG $0x08c28348               // add    rdx, 8
	WORD $0x3948; BYTE $0xd7       // cmp    rdi, rdx
	JNE  LBB0_26
	WORD $0x8948; BYTE $0xfb       // mov    rbx, rdi
	WORD $0x394c; BYTE $0xff       // cmp    rdi, r15
	JE   LBB0_13
	JMP  LBB0_28

LBB0_33:
	SUBQ $8, SP
	VZEROUPPER
	RET

LBB0_34:
	WORD $0xdb31     // xor    ebx, ebx
	LONG $0x01c2f641 // test    r10b, 1
	JNE  LBB0_7
	JMP  LBB0_8

TEXT ·_quick_feed(SB), $0-40

	MOVQ hidden_outputs+0(FP), DI
	MOVQ hidden_outputs_len+8(FP), SI
	MOVQ weights+16(FP), DX
	MOVQ weights_len+24(FP), CX
	MOVQ res+32(FP), R8

	WORD $0xc985             // test    ecx, ecx
	JLE  LBB1_1
	WORD $0x8941; BYTE $0xca // mov    r10d, ecx
	WORD $0x3145; BYTE $0xc9 // xor    r9d, r9d
	WORD $0xf983; BYTE $0x20 // cmp    ecx, 32
	JAE  LBB1_4
	WORD $0xc931             // xor    ecx, ecx
	WORD $0xf631             // xor    esi, esi
	JMP  LBB1_7

LBB1_1:
	WORD $0xf631 // xor    esi, esi
	JMP  LBB1_8

LBB1_4:
	WORD $0x8944; BYTE $0xd1     // mov    ecx, r10d
	WORD $0xe183; BYTE $0xe0     // and    ecx, -32
	LONG $0xef3941c4; BYTE $0xc0 // vpxor    xmm8, xmm8, xmm8
	WORD $0xf631                 // xor    esi, esi
	LONG $0xc9eff1c5             // vpxor    xmm1, xmm1, xmm1
	LONG $0xd2efe9c5             // vpxor    xmm2, xmm2, xmm2
	LONG $0xdbefe1c5             // vpxor    xmm3, xmm3, xmm3
	LONG $0xe4efd9c5             // vpxor    xmm4, xmm4, xmm4

LBB1_5:
	LONG $0x2ceeb9c5; BYTE $0x77   // vpmaxsw    xmm5, xmm8, oword [rdi + 2*rsi]
	LONG $0x74eeb9c5; WORD $0x1077 // vpmaxsw    xmm6, xmm8, oword [rdi + 2*rsi + 16]
	LONG $0x7ceeb9c5; WORD $0x2077 // vpmaxsw    xmm7, xmm8, oword [rdi + 2*rsi + 32]
	LONG $0x44eeb9c5; WORD $0x3077 // vpmaxsw    xmm0, xmm8, oword [rdi + 2*rsi + 48]
	LONG $0x2cd5d1c5; BYTE $0x72   // vpmullw    xmm5, xmm5, oword [rdx + 2*rsi]
	LONG $0xc9fdd1c5               // vpaddw    xmm1, xmm5, xmm1
	LONG $0x6cd5c9c5; WORD $0x1072 // vpmullw    xmm5, xmm6, oword [rdx + 2*rsi + 16]
	LONG $0xd2fdd1c5               // vpaddw    xmm2, xmm5, xmm2
	LONG $0x6cd5c1c5; WORD $0x2072 // vpmullw    xmm5, xmm7, oword [rdx + 2*rsi + 32]
	LONG $0x44d5f9c5; WORD $0x3072 // vpmullw    xmm0, xmm0, oword [rdx + 2*rsi + 48]
	LONG $0xdbfdd1c5               // vpaddw    xmm3, xmm5, xmm3
	LONG $0xe4fdf9c5               // vpaddw    xmm4, xmm0, xmm4
	LONG $0x20c68348               // add    rsi, 32
	WORD $0x3948; BYTE $0xf1       // cmp    rcx, rsi
	JNE  LBB1_5
	LONG $0xc1fde9c5               // vpaddw    xmm0, xmm2, xmm1
	LONG $0xc0fde1c5               // vpaddw    xmm0, xmm3, xmm0
	LONG $0xc0fdd9c5               // vpaddw    xmm0, xmm4, xmm0
	LONG $0xc870f9c5; BYTE $0xee   // vpshufd    xmm1, xmm0, 238
	LONG $0xc1fdf9c5               // vpaddw    xmm0, xmm0, xmm1
	LONG $0xc870f9c5; BYTE $0x55   // vpshufd    xmm1, xmm0, 85
	LONG $0xc1fdf9c5               // vpaddw    xmm0, xmm0, xmm1
	LONG $0xd072f1c5; BYTE $0x10   // vpsrld    xmm1, xmm0, 16
	LONG $0xc1fdf9c5               // vpaddw    xmm0, xmm0, xmm1
	LONG $0xc67ef9c5               // vmovd    esi, xmm0
	WORD $0x394c; BYTE $0xd1       // cmp    rcx, r10
	JE   LBB1_8

LBB1_7:
	LONG $0x4f04b70f             // movzx    eax, word [rdi + 2*rcx]
	WORD $0x8566; BYTE $0xc0     // test    ax, ax
	LONG $0xc1480f41             // cmovs    eax, r9d
	LONG $0x04af0f66; BYTE $0x4a // imul    ax, word [rdx + 2*rcx]
	WORD $0xc601                 // add    esi, eax
	LONG $0x01c18348             // add    rcx, 1
	WORD $0x3949; BYTE $0xca     // cmp    r10, rcx
	JNE  LBB1_7

LBB1_8:
	LONG $0x30894166 // mov    word [r8], si
	RET
