name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Setup GCC Go
      run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test & sudo apt install -y gccgo-11 & sudo cp $(which gccgo-11) $(which gccgo-11 | sed s/-11//g)

    - name: Build
      run: make build

    - name: Test
      run: make test
